/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import modelo.Login;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.ImageIcon;
/**
 *
 * @author CESAR DIAZ MARADIAGA
 */
public class ILogin extends javax.swing.JFrame {
    int x=0, y=0;
    ImageIcon img;
    /**
     * Creates new form ILogin
     */
    public ILogin() {
        initComponents();
        img = new ImageIcon(this.getClass().getResource("/img/iconUpdate2.png"));
        setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                espera = new javax.swing.JDialog();
                jPanel4 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jdPrecioDolar = new javax.swing.JDialog();
                jLabel2 = new javax.swing.JLabel();
                jsPrecioVentaDolar = new javax.swing.JSpinner();
                jLabel5 = new javax.swing.JLabel();
                jsPrecioCompraDolar = new javax.swing.JSpinner();
                lblFechaPrecioDolar = new javax.swing.JLabel();
                btnSetPrecioDolar = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtNombreUsuario = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtPassUsuario = new javax.swing.JPasswordField();
                btnAceptar = new javax.swing.JButton();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();

                espera.setUndecorated(true);

                jPanel4.setBackground(new java.awt.Color(255, 255, 255));

                jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setText("Espere por favor....");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28))
                );

                javax.swing.GroupLayout esperaLayout = new javax.swing.GroupLayout(espera.getContentPane());
                espera.getContentPane().setLayout(esperaLayout);
                esperaLayout.setHorizontalGroup(
                        esperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(esperaLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                esperaLayout.setVerticalGroup(
                        esperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(esperaLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                );

                jdPrecioDolar.setTitle("Precio de dólar");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                jLabel2.setText("Precio venta dólar:");

                jsPrecioVentaDolar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                jsPrecioVentaDolar.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 0.01f));

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                jLabel5.setText("Precio comp dólar:");

                jsPrecioCompraDolar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                jsPrecioCompraDolar.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 0.01f));

                lblFechaPrecioDolar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                lblFechaPrecioDolar.setForeground(new java.awt.Color(0, 153, 0));
                lblFechaPrecioDolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblFechaPrecioDolar.setToolTipText("");

                btnSetPrecioDolar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                btnSetPrecioDolar.setText("Aceptar");

                javax.swing.GroupLayout jdPrecioDolarLayout = new javax.swing.GroupLayout(jdPrecioDolar.getContentPane());
                jdPrecioDolar.getContentPane().setLayout(jdPrecioDolarLayout);
                jdPrecioDolarLayout.setHorizontalGroup(
                        jdPrecioDolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdPrecioDolarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jdPrecioDolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSetPrecioDolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFechaPrecioDolar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdPrecioDolarLayout.createSequentialGroup()
                                                .addGroup(jdPrecioDolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jdPrecioDolarLayout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jsPrecioVentaDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jdPrecioDolarLayout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jsPrecioCompraDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jdPrecioDolarLayout.setVerticalGroup(
                        jdPrecioDolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdPrecioDolarLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblFechaPrecioDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdPrecioDolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jsPrecioVentaDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdPrecioDolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jsPrecioCompraDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSetPrecioDolar)
                                .addContainerGap(10, Short.MAX_VALUE))
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(0, 222, 171));
                setResizable(false);
                addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                formMouseDragged(evt);
                        }
                });
                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                formMousePressed(evt);
                        }
                });

                jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 222, 171)));
                jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setToolTipText("");
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(234, 190, 63));
                jLabel1.setText("CDSOFT");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo.png"))); // NOI18N
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 136, -1, 40));

                txtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                txtNombreUsuario.setForeground(new java.awt.Color(234, 190, 63));
                txtNombreUsuario.setText("Usuario");
                txtNombreUsuario.setBorder(null);
                jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 220, 30));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 223, 40, 40));

                txtPassUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                txtPassUsuario.setForeground(new java.awt.Color(234, 190, 63));
                txtPassUsuario.setText("cdsoft");
                txtPassUsuario.setBorder(null);
                jPanel1.add(txtPassUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, 30));

                btnAceptar.setBackground(new java.awt.Color(234, 190, 63));
                btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
                btnAceptar.setText("Acceder");
                btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnAceptar.setFocusable(false);
                btnAceptar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAceptarActionPerformed(evt);
                        }
                });
                jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 270, 40));

                jSeparator1.setBackground(new java.awt.Color(234, 190, 63));
                jSeparator1.setForeground(new java.awt.Color(234, 190, 63));
                jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 220, 10));

                jSeparator2.setBackground(new java.awt.Color(234, 190, 63));
                jSeparator2.setForeground(new java.awt.Color(234, 190, 63));
                jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 220, 10));

                jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 370, 400));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x, point.y-y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ILogin().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JButton btnAceptar;
        public javax.swing.JButton btnSetPrecioDolar;
        public javax.swing.JDialog espera;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        public javax.swing.JDialog jdPrecioDolar;
        public javax.swing.JSpinner jsPrecioCompraDolar;
        public javax.swing.JSpinner jsPrecioVentaDolar;
        public javax.swing.JLabel lblFechaPrecioDolar;
        public javax.swing.JTextField txtNombreUsuario;
        public javax.swing.JPasswordField txtPassUsuario;
        // End of variables declaration//GEN-END:variables
}
